AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 180

Style/Documentation:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/WordArray:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
