require: rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.6

Layout/LineLength:
  Max: 180

Style/Documentation:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/Not:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/ImplicitSubject:
  EnforcedStyle: single_statement_only
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NestedGroups:
  Max: 5
